### ISSUE TITLE
getText (& other) event functions

### ISSUE THREAD

**Issue by joelmccracken** [dwhitney/purescript-react-basic-native#11]
I lifted `getText` from one of your examples for something I am working on:

```
getText :: EventFn SyntheticEvent (Maybe String)
getText = unsafeEventFn \e ->
  toMaybe (unsafeCoerce e).nativeEvent.text
```

**Comment by spicydonuts** [comment]
Nice, does the EventFn stuff make sense?

**Comment by dwhitney** [comment]
hmmm... I think this will only work for `TextInput` components when the `onChange` event is fired. Check out #5 - this will enable type safety on all of the events along with exposing type safe ways of creating many objects like `StyleProps<ViewStyle>`. I'd say I'm about 80% done with it in the event branch. Hopefully I'll be done by this weekend.

@spicydonuts yes the EventFn's work! In master it's necessary to unsafeCoerce them all, which sucks, but the above will fix that.

I'm going to close this issue since it's basically the same thing as #5
